print("My name is Adeyemi Kayode")
print("My email address is 'adeyemikayode399@gmail.com'")
print("The language I used for this self introduction is python")
print("My slack username is 'Adeyemi Kayode'")
print("Please I also want you to know that my Biostack is'drug discovery'")print("My name is Adeyemi Kayode")
print("My email address is 'adeyemikayode399@gmail.com'")
print("The language I used for this self introduction is python")
print("My slack username is 'Adeyemi Kayode'")
print("Please I also want you to know that my Biostack is'drug discovery'")